export const arrayChildrenOfFolderThree = [
  {
    'idFolder': 2,
    'idParent': 0,
    'numberAgreement': 'Абонентское дело 1',
    'numberSubscriber': 1,
    'folderLevel': 1,
    'comments': 'level1',
  },
  {
    'idFolder': 3,
    'idParent': 0,
    'numberAgreement': 'Абонентское дело 2',
    'numberSubscriber': 2,
    'folderLevel': 1,
    'comments': 'level1',
  },
  {
    'idFolder': 4,
    'idParent': 0,
    'numberAgreement': 'Абонентское дело 3',
    'numberSubscriber': 3,
    'folderLevel': 1,
    'comments': 'level1',
  },
  {
    'idFolder': 5,
    'idParent': 3,
    'numberAgreement': 'Абонентское дело 3.1',
    'numberSubscriber': 5,
    'folderLevel': 2,
    'comments': 'level2',
  },
  {
    'idFolder': 6,
    'idParent': 3,
    'numberAgreement': 'Абонентское дело 3.2',
    'numberSubscriber': 6,
    'folderLevel': 2,
    'comments': 'level2',
  },
  {
    'idFolder': 7,
    'idParent': 1,
    'numberAgreement': 'Проектно-техническая документация 1',
    'numberSubscriber': 4,
    'folderLevel': 1,
    'comments': 'level1',
  },
];
