export const arrayChildrenOfFolderThree = [
  {
    'idFolder': 2,
    'idParent': 0,
    'numberAgreement': 'Абонентское дело 1',
    'numberSubscriber': 1,
    'folderLevel': 1,
    'comments': 'level1',
  },
  {
    'idFolder': 3,
    'idParent': 2,
    'numberAgreement': 'проектно-техническая документация',
    'numberSubscriber': 1,
    'folderLevel': 2,
    'comments': 'level1',
  },
  {
    'idFolder': 4,
    'idParent': 2,
    'numberAgreement': 'учредительные и рег документы',
    'numberSubscriber': 1,
    'folderLevel': 2,
    'comments': 'level1',
  },
  {
    'idFolder': 5,
    'idParent': 2,
    'numberAgreement': 'акты ко',
    'numberSubscriber': 1,
    'folderLevel': 2,
    'comments': 'level1',
  },
  {
    'idFolder': 6,
    'idParent': 2,
    'numberAgreement': 'договор',
    'numberSubscriber': 1,
    'folderLevel': 2,
    'comments': 'level1',
  },
  {
    'idFolder': 7,
    'idParent': 2,
    'numberAgreement': 'письма-жалобы абонентов и ответы',
    'numberSubscriber': 1,
    'folderLevel': 2,
    'comments': 'level1',
  },
  {
    'idFolder': 8,
    'idParent': 2,
    'numberAgreement': 'служ записи, рапорты',
    'numberSubscriber': 1,
    'folderLevel': 2,
    'comments': 'level1',
  },
  {
    'idFolder': 9,
    'idParent': 2,
    'numberAgreement': 'прочие документы',
    'numberSubscriber': 1,
    'folderLevel': 2,
    'comments': 'level1',
  },
  {
    'idFolder': 10,
    'idParent': 0,
    'numberAgreement': 'Абонентское дело 2',
    'numberSubscriber': 2,
    'folderLevel': 1,
    'comments': 'level1',
  },
  {
    'idFolder': 11,
    'idParent': 10,
    'numberAgreement': 'проектно-техническая документация',
    'numberSubscriber': 2,
    'folderLevel': 2,
    'comments': 'level1',
  },
  {
    'idFolder': 12,
    'idParent': 10,
    'numberAgreement': 'учредительные и рег документы',
    'numberSubscriber': 2,
    'folderLevel': 2,
    'comments': 'level1',
  },
  {
    'idFolder': 13,
    'idParent': 10,
    'numberAgreement': 'акты ко',
    'numberSubscriber': 2,
    'folderLevel': 2,
    'comments': 'level1',
  },
  {
    'idFolder': 14,
    'idParent': 10,
    'numberAgreement': 'договор',
    'numberSubscriber': 2,
    'folderLevel': 2,
    'comments': 'level1',
  },
  {
    'idFolder': 15,
    'idParent': 10,
    'numberAgreement': 'письма-жалобы абонентов и ответы',
    'numberSubscriber': 2,
    'folderLevel': 2,
    'comments': 'level1',
  },
  {
    'idFolder': 16,
    'idParent': 10,
    'numberAgreement': 'служ записи, рапорты',
    'numberSubscriber': 2,
    'folderLevel': 2,
    'comments': 'level1',
  },
  {
    'idFolder': 17,
    'idParent': 10,
    'numberAgreement': 'прочие документы',
    'numberSubscriber': 2,
    'folderLevel': 2,
    'comments': 'level1',
  },
  {
    'idFolder': 18,
    'idParent': 1,
    'numberAgreement': 'Проектно-техническая документация 1',
    'numberSubscriber': 4,
    'folderLevel': 1,
    'comments': 'level1',
  },
  {
    'idFolder': 19,
    'idParent': 18,
    'numberAgreement': 'проектно-техническая документация',
    'numberSubscriber': 4,
    'folderLevel': 2,
    'comments': 'level1',
  },
  {
    'idFolder': 20,
    'idParent': 18,
    'numberAgreement': 'учредительные и рег документы',
    'numberSubscriber': 4,
    'folderLevel': 2,
    'comments': 'level1',
  },
  {
    'idFolder': 21,
    'idParent': 18,
    'numberAgreement': 'акты ко',
    'numberSubscriber': 4,
    'folderLevel': 2,
    'comments': 'level1',
  },
  {
    'idFolder': 22,
    'idParent': 18,
    'numberAgreement': 'договор',
    'numberSubscriber': 4,
    'folderLevel': 2,
    'comments': 'level1',
  },
  {
    'idFolder': 23,
    'idParent': 18,
    'numberAgreement': 'письма-жалобы абонентов и ответы',
    'numberSubscriber': 4,
    'folderLevel': 2,
    'comments': 'level1',
  },
  {
    'idFolder': 24,
    'idParent': 18,
    'numberAgreement': 'служ записи, рапорты',
    'numberSubscriber': 4,
    'folderLevel': 2,
    'comments': 'level1',
  },
  {
    'idFolder': 25,
    'idParent': 18,
    'numberAgreement': 'прочие документы',
    'numberSubscriber': 4,
    'folderLevel': 2,
    'comments': 'level1',
  },
];
